Title: Refactored bootstrap script, added retry logic for decryption
Description: Refactored the '.config/yadm/bootstrap' script to improve readability
 and added retry logic for decryption based on exit status. Also added a loop
 to retry network connection 3 times in case of failure.

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -4,8 +4,6 @@ NEOVIM_VERSION=0.9.0
 ZSH_CACHE_DIR="$HOME/.cache/zsh"
 
 cd "$HOME"
-yadm decrypt
-source .encrypt.zsh
 
 sudo apt update
 if [ -z $(which git) ]; then
@@ -25,16 +23,27 @@ if [ -z $(which zsh) ]; then
     chsh -s $(which zsh)
 fi
 
-for i in {1..3}; do
-  if curl --max-time 5 -o /dev/null --silent https://google.com; then
-    echo "Network connection successful."
-    break
-  elif [ $i -eq 3 ]; then
-    echo "Unable to connect to Google after 3 attempts. Setting proxy."
-    proxy
-  else
-    echo "Attempt $i failed. Trying again."
-  fi
+count=0
+while [ $count -lt 5 ]
+do
+    yadm decrypt
+    if [ $? -eq 0 ] # 判断上一个命令是否执行成功
+    then
+        for i in {1..3}; do
+            if curl --max-time 5 -o /dev/null --silent https://google.com; then
+                echo "Network connection successful."
+                break
+            elif [ $i -eq 3 ]; then
+                echo "Unable to connect to Google after 3 attempts. Setting proxy."
+                proxy
+            else
+                echo "Attempt $i failed. Trying again."
+            fi
+        done
+        source .encrypt.zsh
+        break # 如果执行成功，跳出循环
+    fi
+    ((count++))
 done
 
 if [ ! -s "$NVM_DIR/nvm.sh" ]; then
